GET http://127.0.0.1:8000/students/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwaWVtaWNhaCIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTc3NDk5MjQ5Nn0.OCtUX5UR3AYBNYGnFesIqKgn8qDSn2f1PEGIlaHssIY

###

POST http://127.0.0.1:8000/users
Content-Type: application/json

{
    "username":"morire",
    "password":"123456",
    "role_id":2
}

###

POST http://127.0.0.1:8000/auth/login-json/
Content-Type: application/json

{
    "username":"piemicah",
    "password":"goodpie222"
}
 

